version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
  - package-ecosystem: cargo
    directory: /native/ubs-helper
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
  - package-ecosystem: cargo
    directory: /desktop/src-tauri
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
