window.UBS_MESSAGES = Object.freeze({
  ko: {
    language: "한국어", skip: "빌드 설정으로 이동", workspace: "작업 공간", build: "빌드",
    localOnly: "로컬 전용", noRemote: "원격 서비스·업로드 없음",
    recentBuilds: "최근 빌드", historyEmpty: "아직 빌드 기록이 없습니다.",
    historySuccess: "완료", historyFailed: "실패", historyCancelled: "취소",
    project: "프로젝트", notDetected: "미감지", chooseFolder: "프로젝트 폴더 추가",
    chooseHint: "프로젝트 또는 모노레포 루트", browse: "찾아보기", detectedProject: "감지된 프로젝트",
    removeProject: "{name} 제거",
    projectSelected: "{name} 선택됨.", projectRemoved: "{name} 제거됨.",
    waitingProject: "프로젝트 선택 대기 중.", detecting: "프로젝트 감지 중…",
    noProjects: "빌드 가능한 프로젝트가 없습니다.", oneProject: "프로젝트 1개 감지.",
    manyProjects: "프로젝트 {count}개 감지. 빌드 대상을 선택하세요.", options: "빌드 옵션",
    safeDefaults: "안전 기본값", versionLabel: "버전", versionNone: "변경 없음",
    versionBuild: "빌드 번호", versionPatch: "패치", versionMinor: "마이너", versionMajor: "메이저",
    jobsLabel: "빌드 방식", jobsSequential: "순차 빌드", jobsParallel: "병렬 빌드", cleanLabel: "클린 빌드",
    cleanHint: "끄면 캐시를 재사용해 빠름", outputsLabel: "Flutter 출력",
    outputsUnavailable: "Flutter 프로젝트에서만 출력 형식을 선택합니다.", outputsReady: "여러 형식 선택 가능.",
    pipeline: "파이프라인", ready: "준비", stageDetect: "감지", stageValidate: "검증",
    stageBuild: "빌드", stagePackage: "패키징", stageDone: "완료",
    guardrail: "비대화형 · 업로드 차단", cancel: "취소", startBuild: "빌드 시작",
    buildLog: "빌드 로그", copyLog: "로그 복사", logCopied: "복사 완료", logCopyFailed: "복사 실패",
    chooseDialog: "UBS 프로젝트 선택", desktopOnly: "데스크톱 앱에서 실행하세요.",
    detectFailed: "프로젝트 감지에 실패했습니다.", building: "빌드 중", cancelling: "취소 중…",
    cancelled: "빌드 취소됨.", succeeded: "빌드 완료.", failed: "빌드 실패 · 종료 코드 {code}",
    artifacts: "산출물 {count}개", openFolder: "폴더 열기", openFolderFailed: "열기 실패",
    noArtifacts: "보고된 산출물 없음", buildError: "빌드를 시작하지 못했습니다."
  },
  en: {
    language: "English", skip: "Skip to build controls", workspace: "Workspace", build: "Build",
    localOnly: "Local only", noRemote: "No remote service or upload",
    recentBuilds: "Recent builds", historyEmpty: "No builds yet.",
    historySuccess: "Done", historyFailed: "Failed", historyCancelled: "Cancelled",
    project: "Project", notDetected: "Not detected", chooseFolder: "Add project folder",
    chooseHint: "A project or monorepo root", browse: "Browse", detectedProject: "Detected project",
    removeProject: "Remove {name}",
    projectSelected: "{name} selected.", projectRemoved: "{name} removed.",
    waitingProject: "Waiting for a project.", detecting: "Detecting projects…",
    noProjects: "No buildable projects found.", oneProject: "1 project detected.",
    manyProjects: "{count} projects detected. Choose one to build.", options: "Build options",
    safeDefaults: "Safe defaults", versionLabel: "Version", versionNone: "No change",
    versionBuild: "Build number", versionPatch: "Patch", versionMinor: "Minor", versionMajor: "Major",
    jobsLabel: "Build mode", jobsSequential: "Sequential build", jobsParallel: "Parallel build", cleanLabel: "Clean rebuild",
    cleanHint: "Off keeps caches for speed", outputsLabel: "Flutter output",
    outputsUnavailable: "Choose a Flutter project to set outputs.", outputsReady: "Multiple formats allowed.",
    pipeline: "Pipeline", ready: "Ready", stageDetect: "Detect", stageValidate: "Validate",
    stageBuild: "Build", stagePackage: "Package", stageDone: "Done",
    guardrail: "Non-interactive · upload disabled", cancel: "Cancel", startBuild: "Start build",
    buildLog: "Build log", copyLog: "Copy log", logCopied: "Copied", logCopyFailed: "Copy failed",
    chooseDialog: "Choose a UBS project", desktopOnly: "Run this inside the desktop app.",
    detectFailed: "Project detection failed.", building: "Building", cancelling: "Cancelling…",
    cancelled: "Build cancelled.", succeeded: "Build complete.", failed: "Build failed · exit {code}",
    artifacts: "{count} artifacts", openFolder: "Open folder", openFolderFailed: "Open failed",
    noArtifacts: "No artifacts reported", buildError: "Could not start the build."
  },
  ja: {
    language: "日本語", skip: "ビルド設定へ移動", workspace: "ワークスペース", build: "ビルド",
    localOnly: "ローカルのみ", noRemote: "外部サービス・アップロードなし",
    recentBuilds: "最近のビルド", historyEmpty: "ビルド履歴はまだありません。",
    historySuccess: "完了", historyFailed: "失敗", historyCancelled: "中止",
    project: "プロジェクト", notDetected: "未検出", chooseFolder: "プロジェクトフォルダを追加",
    chooseHint: "プロジェクトまたはモノレポのルート", browse: "参照", detectedProject: "検出したプロジェクト",
    removeProject: "{name} を削除",
    projectSelected: "{name} を選択しました。", projectRemoved: "{name} を削除しました。",
    waitingProject: "プロジェクトの選択待ちです。", detecting: "プロジェクトを検出中…",
    noProjects: "ビルド可能なプロジェクトがありません。", oneProject: "1 件のプロジェクトを検出。",
    manyProjects: "{count} 件を検出。ビルド対象を選択してください。", options: "ビルド設定",
    safeDefaults: "安全な初期値", versionLabel: "バージョン", versionNone: "変更なし",
    versionBuild: "ビルド番号", versionPatch: "パッチ", versionMinor: "マイナー", versionMajor: "メジャー",
    jobsLabel: "ビルド方式", jobsSequential: "順次ビルド", jobsParallel: "並列ビルド", cleanLabel: "クリーンビルド",
    cleanHint: "オフでキャッシュを再利用", outputsLabel: "Flutter 出力",
    outputsUnavailable: "Flutter プロジェクトで出力を選択できます。", outputsReady: "複数選択できます。",
    pipeline: "パイプライン", ready: "準備完了", stageDetect: "検出", stageValidate: "検証",
    stageBuild: "ビルド", stagePackage: "パッケージ", stageDone: "完了",
    guardrail: "非対話式 · アップロード無効", cancel: "中止", startBuild: "ビルド開始",
    buildLog: "ビルドログ", copyLog: "ログをコピー", logCopied: "コピーしました", logCopyFailed: "コピー失敗",
    chooseDialog: "UBS プロジェクトを選択", desktopOnly: "デスクトップアプリで実行してください。",
    detectFailed: "プロジェクトを検出できませんでした。", building: "ビルド中", cancelling: "中止中…",
    cancelled: "ビルドを中止しました。", succeeded: "ビルド完了。", failed: "ビルド失敗 · 終了 {code}",
    artifacts: "成果物 {count} 件", openFolder: "フォルダを開く", openFolderFailed: "開けません",
    noArtifacts: "成果物の報告なし", buildError: "ビルドを開始できませんでした。"
  },
  zh: {
    language: "简体中文", skip: "跳到构建设置", workspace: "工作区", build: "构建",
    localOnly: "仅限本机", noRemote: "无远程服务或上传",
    recentBuilds: "最近构建", historyEmpty: "暂无构建记录。",
    historySuccess: "完成", historyFailed: "失败", historyCancelled: "已取消",
    project: "项目", notDetected: "未检测", chooseFolder: "添加项目文件夹",
    chooseHint: "项目或单体仓库根目录", browse: "浏览", detectedProject: "检测到的项目",
    removeProject: "移除 {name}",
    projectSelected: "已选择 {name}。", projectRemoved: "已移除 {name}。",
    waitingProject: "等待选择项目。", detecting: "正在检测项目…",
    noProjects: "未找到可构建项目。", oneProject: "检测到 1 个项目。",
    manyProjects: "检测到 {count} 个项目，请选择构建目标。", options: "构建选项",
    safeDefaults: "安全默认值", versionLabel: "版本", versionNone: "不更改",
    versionBuild: "构建号", versionPatch: "补丁", versionMinor: "次版本", versionMajor: "主版本",
    jobsLabel: "构建方式", jobsSequential: "顺序构建", jobsParallel: "并行构建", cleanLabel: "全新构建",
    cleanHint: "关闭可复用缓存", outputsLabel: "Flutter 输出",
    outputsUnavailable: "选择 Flutter 项目后可设置输出。", outputsReady: "可选择多个格式。",
    pipeline: "流程", ready: "就绪", stageDetect: "检测", stageValidate: "验证",
    stageBuild: "构建", stagePackage: "打包", stageDone: "完成",
    guardrail: "非交互 · 禁止上传", cancel: "取消", startBuild: "开始构建",
    buildLog: "构建日志", copyLog: "复制日志", logCopied: "已复制", logCopyFailed: "复制失败",
    chooseDialog: "选择 UBS 项目", desktopOnly: "请在桌面应用中运行。",
    detectFailed: "项目检测失败。", building: "构建中", cancelling: "正在取消…",
    cancelled: "构建已取消。", succeeded: "构建完成。", failed: "构建失败 · 退出码 {code}",
    artifacts: "{count} 个产物", openFolder: "打开文件夹", openFolderFailed: "打开失败",
    noArtifacts: "未报告产物", buildError: "无法开始构建。"
  }
});
